'use client';

import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font
Font.register({
    family: 'Helvetica',
    fonts: [
        { src: 'https://fonts.gstatic.com/s/helvetica/v1/Helvetica.ttf' },
        { src: 'https://fonts.gstatic.com/s/helvetica/v1/Helvetica-Bold.ttf', fontWeight: 'bold' },
    ]
});

const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        borderBottom: 1,
        borderBottomColor: '#E5E7EB',
        paddingBottom: 10,
    },
    title: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    subtitle: {
        fontSize: 10,
        color: '#6B7280',
    },
    content: {
        fontSize: 11,
        lineHeight: 1.5,
        color: '#374151',
        textAlign: 'justify',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        fontSize: 9,
        color: '#9CA3AF',
        textAlign: 'center',
        borderTop: 1,
        borderTopColor: '#F3F4F6',
        paddingTop: 10,
    },
});

interface PdfDocumentViewProps {
    title: string;
    content: string;
    author?: string;
    jobTitle?: string;
    companyName?: string;
}

export function PdfDocumentView({ title, content, author, jobTitle, companyName }: PdfDocumentViewProps) {
    const formattedDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>{author || 'Candidate'}</Text>
                    <Text style={styles.subtitle}>
                        {jobTitle ? `${jobTitle} application` : 'Job Application'}
                        {companyName ? ` at ${companyName}` : ''}
                    </Text>
                    <Text style={{ ...styles.subtitle, marginTop: 4 }}>{formattedDate}</Text>
                </View>

                <View>
                    <Text style={styles.content}>
                        {content}
                    </Text>
                </View>

                <View style={styles.footer}>
                    <Text>Generated by CareerAI • {title}</Text>
                </View>
            </Page>
        </Document>
    );
}
